name: myapp-ci

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # Optional but recommended for faster installs:
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure pytest is available if it's not in requirements.txt
          pip install pytest

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest -q

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 linter
        run: |
          # Lint the specific file or the whole src folder
          flake8 src/app.py
          # or: flake8 src --count --max-line-length=88 --statistics

