name: myapp-ci

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          # Your requirements file is under src/
          cache-dependency-path: src/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Smoke import (no tests folder)
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python - <<'PY'
          import sys
          sys.path.append('src')
          import app  # noqa: F401
          print("✅ app imported successfully")
          PY

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # If you want CI to auto-fix formatting before linting, uncomment this:
      # - name: Autoformat with Black (optional)
      #   run: black src/app.py

      - name: Black formatting check
        run: black --check src/app.py

      - name: Run flake8
        run: flake8 src/app.py

